#include <iostream>
#include <fstream>
#include <cstring>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/conf.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <sqlite3.h>
#include "crypt.h"
#include "db.h"